"""Search research gaps with Tavily and hand results back to the main session."""

from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

import requests


HANDOFF_MESSAGE = "=== 搜索完成，请将以上结果粘贴给主会话 Claude 进行提炼 ==="
TAVILY_ENDPOINT = "https://api.tavily.com/search"


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run Tavily multi-query search for research task bundles."
    )
    parser.add_argument(
        "--tasks-json",
        type=Path,
        help="Path to task JSON generated by blank_identifier.py. If omitted, read from stdin.",
    )
    parser.add_argument(
        "--json-out",
        type=Path,
        help="Optional output path for structured Tavily results JSON.",
    )
    parser.add_argument(
        "--max-results-per-query",
        type=int,
        default=5,
        help="Maximum Tavily results fetched per query. Default: 5.",
    )
    parser.add_argument(
        "--timeout",
        type=float,
        default=20.0,
        help="HTTP timeout in seconds. Default: 20.",
    )
    return parser.parse_args(argv)


def fail(message: str) -> "NoReturn":
    print(message, file=sys.stderr)
    raise SystemExit(1)


def require_api_key() -> str:
    api_key = os.getenv("TAVILY_API_KEY", "").strip()
    if not api_key:
        fail("缺少 Tavily API 密钥，请先执行: export TAVILY_API_KEY=your_key")
    return api_key


def load_tasks(path: Path | None) -> dict[str, Any]:
    try:
        raw = path.read_text(encoding="utf-8") if path else sys.stdin.read()
    except OSError as exc:
        fail(f"读取研究任务 JSON 失败: {exc}")

    if not raw.strip():
        fail("未提供研究任务 JSON。请传入 --tasks-json 或通过 stdin 输入。")

    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as exc:
        fail(f"研究任务 JSON 解析失败: {exc}")

    if not isinstance(payload, dict):
        fail("研究任务 JSON 顶层必须是对象。")
    tasks = payload.get("tasks")
    if not isinstance(tasks, list):
        fail("研究任务 JSON 缺少 tasks 数组。")
    return payload


def _compact_text(value: Any) -> str:
    if isinstance(value, str):
        return " ".join(value.split())
    if isinstance(value, list):
        return " ".join(_compact_text(item) for item in value if _compact_text(item))
    if value is None:
        return ""
    return " ".join(str(value).split())


def build_queries(task: dict[str, Any]) -> list[str]:
    topic = _compact_text(task.get("topic"))
    research_question = _compact_text(task.get("research_question"))
    blank_type = _compact_text(task.get("blank_type"))
    evidence = _compact_text(task.get("supporting_evidence", []))
    signals = _compact_text(task.get("signals", []))

    candidates = [
        f"{topic} {research_question}".strip(),
        f"{topic} 最佳实践 案例 教程 {blank_type}".strip(),
        f"{topic} {evidence} {signals}".strip(),
    ]

    queries: list[str] = []
    seen: set[str] = set()
    for candidate in candidates:
        query = " ".join(candidate.split())
        if not query or query in seen:
            continue
        seen.add(query)
        queries.append(query)
    return queries[:3]


def search_query(
    api_key: str,
    gap_id: str,
    query: str,
    max_results: int,
    timeout: float,
) -> list[dict[str, Any]]:
    payload = {
        "api_key": api_key,
        "query": query,
        "search_depth": "advanced",
        "max_results": max_results,
        "include_answer": False,
        "include_raw_content": False,
    }
    try:
        response = requests.post(TAVILY_ENDPOINT, json=payload, timeout=timeout)
        response.raise_for_status()
        data = response.json()
    except requests.RequestException as exc:
        fail(f"Tavily 搜索失败（gap_id={gap_id}, query={query}）: {exc}")
    except ValueError as exc:
        fail(f"Tavily 返回了无法解析的 JSON（gap_id={gap_id}, query={query}）: {exc}")

    results = data.get("results", [])
    if not isinstance(results, list):
        return []

    normalized: list[dict[str, Any]] = []
    for item in results:
        if not isinstance(item, dict):
            continue
        normalized.append(
            {
                "gap_id": gap_id,
                "query": query,
                "url": str(item.get("url", "")).strip(),
                "title": str(item.get("title", "")).strip(),
                "content": str(item.get("content", "")).strip(),
                "relevance_score": float(item.get("score", 0.0) or 0.0),
            }
        )
    normalized.sort(key=lambda item: item["relevance_score"], reverse=True)
    return normalized


def build_result_bundle(payload: dict[str, Any], api_key: str, args: argparse.Namespace) -> dict[str, Any]:
    tasks = payload.get("tasks", [])
    results: list[dict[str, Any]] = []
    query_count = 0

    for task in tasks:
        if not isinstance(task, dict):
            continue
        gap_id = str(task.get("task_id", "")).strip() or "unknown-gap"
        for query in build_queries(task):
            query_count += 1
            results.extend(
                search_query(
                    api_key=api_key,
                    gap_id=gap_id,
                    query=query,
                    max_results=args.max_results_per_query,
                    timeout=args.timeout,
                )
            )

    results.sort(key=lambda item: (item["gap_id"], -item["relevance_score"], item["url"]))
    return {
        "generated_at": datetime.now().astimezone().isoformat(timespec="seconds"),
        "task_count": len([task for task in tasks if isinstance(task, dict)]),
        "query_count": query_count,
        "result_count": len(results),
        "results": results,
    }


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    api_key = require_api_key()
    payload = load_tasks(args.tasks_json)
    result_bundle = build_result_bundle(payload, api_key, args)
    json_text = json.dumps(result_bundle, ensure_ascii=False, indent=2)

    if args.json_out:
        try:
            args.json_out.write_text(json_text + "\n", encoding="utf-8")
        except OSError as exc:
            fail(f"写入搜索结果 JSON 失败: {exc}")

    print(json_text)
    print(HANDOFF_MESSAGE)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
